#!/usr/bin/env python

from chdrft.waf.opa import WafBuilder


x = WafBuilder(globals())
x.register_libs(x.libs.Common_N, x.packages.Json, x.packages.GPMFParser, x.packages.Ceres, x.packages.Eigen)

x.auto()
x.setup()
